---
- hosts: all
  remote_user: pi

  vars:
    xkblayout: "fr"
  
  tasks:
    - name: Create user alc
      become: yes
      user:
        name: "{{ username }}"
        shell: /bin/bash
        password: "{{ password }}"

    - name: Update raspi-config
      become: true
      apt: name=raspi-config cache_valid_time=3600

    - name: Change keyboard layout
      shell: "raspi-config nonint do_configure_keyboard {{ xkblayout }}"

  vars_prompt:
    - name: "username"
      prompt: "Username"
      private: no
    - name: "password"
      prompt: "Password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
