---
- hosts: all

  vars:
    timezone: Europe/Paris
  
  tasks:
    - name: Set timezone
      timezone: name={{ timezone }}
      become: yes

    - name: Start time services
      service: name=systemd-timesyncd state=started enabled=yes
      become: yes

    - name: Run timedatectl status
      command: timedatectl status
      changed_when: false
      register: timedatectl_result

    - name: Enable ntp
      command: timedatectl set-ntp true
      when: "'NTP service: inactive' in timedatectl_result.stdout"
      become: yes
